server: 
    port: 8080

spring:
  datasource:
    url: ${DATABASE_URL_RENDER}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    initialize: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres