server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mavie
        username: postgres
        password: fantasma
        driver-class-name: org.postgresql.Driver
        initialize: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres