server: 
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d4dqaejuibrs739vfbng-a.oregon-postgres.render.com:5432/aula_y4qy
    username: aula_y4qy_user
    password: t5m9rbKLBVd35RSo9BXgFqzTMJ7Pp3ga
    driver-class-name: org.postgresql.Driver
    initialize: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres